<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>Template.BlazorWasm</RootNamespace>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <PropertyGroup>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingPlatformShowTestsFailure>true</TestingPlatformShowTestsFailure>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bunit" Version="2.9.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.6.2" />
    <PackageReference Include="Usa.Smart.Mock.Data" Version="2.10.0" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Template.BlazorWasm.Backend.Core\Template.BlazorWasm.Backend.Core.csproj" />
    <ProjectReference Include="..\Template.BlazorWasm.Backend.Web\Template.BlazorWasm.Backend.Web.csproj" />
    <ProjectReference Include="..\Template.BlazorWasm.Domain\Template.BlazorWasm.Domain.csproj" />
    <ProjectReference Include="..\Template.BlazorWasm.Frontend\Template.BlazorWasm.Frontend.csproj" />
    <ProjectReference Include="..\Template.BlazorWasm.Shared\Template.BlazorWasm.Shared.csproj" />
  </ItemGroup>

</Project>
