<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Template.BlazorWasm</RootNamespace>
    <CodeAnalysisRuleSet>..\Analyzers.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Usa.Smart.Core" Version="2.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Template.BlazorWasm.Domain\Template.BlazorWasm.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Usa.Smart.Analyzers.JapaneseComment" Version="1.10.0" />
  </ItemGroup>

</Project>
